title: beszelnijo
url: "https://www.beszelnijo.hu"
baseurl: /
permalink: '/:title/'
layout_style: overflow
palette: 
logo: "images/speaking.png"
locale: "hu"
# Google Analytics
ga_track_id: 'G-28B92VCC9R'
ga_domain: huangxuan.me

header:
  has_nav: true
  nav_links:
    - label: Kezdőoldal
      url: /
      style: link
    - label: Rólam
      url: /rolam/
      style: link
    - label: Rólam mondták
      url: /rolammondtak/
      style: link
    - label: Cikkek
      url: /cikkek/
      style: link
    - label: Írások
      url: /irasok/
      style: link
    - label: Kapcsolat
      url: /kapcsolat/
      style: link
  has_social: true
  social_links:
    - label: facebook
      url: https://www.facebook.com/SzaboAgnes89/
      style: icon
      icon_class: facebook
      new_window: true
footer:
  content: >-
    © Minden jog fenntartva - 2021 | <a href="/gdpr">GDPR</a>
sass:
  indentWidth: 4
  style: nested
  precision: 10
  sass_dir: _sass

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
